version: '3.9'
services:
  rabbitmq:
    ports:
    - "15672:15672"
    - "5672:5672"
    image: "rabbitmq:3.8-management-alpine"
  
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    command: -js
  
  redis:
    image: bitnami/redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --protected-mode no
    volumes: 
      - redis:/data

  pubsub:
    image: google/cloud-sdk:latest
    command: ["gcloud", "beta", "emulators", "pubsub", "start", "--host-port=0.0.0.0:8085"]
    ports:
      - "8085:8085"

  sqs:
    image: softwaremill/elasticmq-native
    ports:
      - "9324:9324"

volumes:
  redis:
    driver: local