name: Go package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services: 
      rabbitmq:
        image: "rabbitmq:3.8-management-alpine"
        ports:
           - "5672:5672"

      nats:
        image: nats
        ports:
           - "4222:4222"
  
      zookeeper:
        image: confluentinc/cp-zookeeper
        ports:
          - "2181:2181"
        env:
          ALLOW_ANONYMOUS_LOGIN: yes
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
        options: >-
          --health-cmd "echo mntr | nc -w 2 -q 2 localhost 2181"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      kafka:
        image: confluentinc/cp-kafka
        ports:
          - "9092:9092"
          - "29092:29092"
        # options: >-
        #   --health-cmd "kafka-broker-api-versions.sh --version"
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin 

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: lint
        run: golangci-lint run
