name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    services: 
      service-name-1:
        image: "rabbitmq:3.8-management-alpine"
        ports:
           - "5672:5672"

      service-name-2:
        image: nats
        ports:
           - "4222:4222"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin 

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: lint
        run: golangci-lint run